# Generated by Django 2.2.1 on 2019-06-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
