# Generated by Django 3.1.2 on 2020-11-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20190628_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
