# Generated by Django 2.2.1 on 2019-05-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_specialty_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Specialty'),
        ),
    ]
