# Generated by Django 2.2.1 on 2019-06-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name_plural': 'specialties'},
        ),
    ]
