# Generated by Django 3.1.2 on 2020-11-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201012_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.ManyToManyField(related_name='users', to='users.Specialty'),
        ),
    ]
