# Generated by Django 2.2.1 on 2019-05-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcomment',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='resolved'),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='resolved'),
        ),
    ]
