# Generated by Django 2.2.1 on 2019-05-31 13:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20190519_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
