# Generated by Django 2.2.1 on 2019-06-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='subject',
            new_name='course',
        ),
    ]
