# Generated by Django 2.2.1 on 2019-06-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exam', to='questions.Question'),
        ),
    ]
