version: '3.7'

version: '3.7'

volumes:
  question_db_data:
  question_staticfiles:

services:
  question_db:
    image: postgres:11.2-alpine
    env_file:
      - ../.env
    ports:
      - 5400:5432
    volumes:
      - question_db_data:/var/lib/postgresql/data

  question_prod:
    build:
      context: ../
      dockerfile: ./docker/prod.Dockerfile
    command: /start
    env_file:
      - ../.env
    depends_on:
      - question_db
    volumes:
      - question_staticfiles:/app/staticfiles

  question_server:
    image: nginx:1.15.8-alpine
    ports:
      - 80:80
    # configs:
    #   - source: tpm_nginx
    #     target: /etc/nginx/nginx.conf
    volumes:
      - question_staticfiles:/staticfiles:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - question_prod
