version: '3'

services:
  question_db:
    image: postgres:11.2-alpine
    env_file:
      - ../.env
    ports:
      - 5400:5432

  question_app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: /start
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - question_db
    ports:
      - 8000:80
