version: '3.7'

configs:
  question_server_config:
    file: ./nginx.conf

volumes:
  question_db_data:
  question_staticfiles:

services:
  question_db:
    image: postgres:11.2-alpine
    env_file:
      - ../.env
    ports:
      - 5400:5432
    volumes:
      - question_db_data:/var/lib/postgresql/data

  question_prod:
    image: docker.pkg.github.com/syafiqtermizi/questionbank/questionbank:latest
    command: poetry run gunicorn -c python:config.gunicorn config.wsgi:application
    env_file:
      - ../.env
    depends_on:
      - question_db
    volumes:
      - question_staticfiles:/app/staticfiles

  question_server:
    image: nginx:1.15.8-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - question_prod

  question_memcached:
    image: memcached:1.5.16-alpine
    ports:
      - 11211:11211
    entrypoint:
     - memcached
     - -m 64
