# Generated by Django 2.2.1 on 2019-07-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0006_auto_20190625_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_index', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Passing Index (PI)')),
                ('discrimination_index', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Discrimination Index (DI)')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
    ]
