# Generated by Django 2.2.1 on 2019-05-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_add_created_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
