# Generated by Django 2.2.1 on 2019-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_auto_20190509_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='role',
            field=models.CharField(
                choices=[
                    ('Admin', 'Admin'),
                    ('Coordinator', 'Coordinator'),
                    ('Lecturer', 'Lecturer')
                ],
                default='Admin', max_length=20
            ),
            preserve_default=False,
        ),
    ]
