# Generated by Django 2.2.1 on 2019-05-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('invites', '0006_invite_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='role',
        ),
        migrations.AddField(
            model_name='invite',
            name='role',
            field=models.ManyToManyField(related_name='invites', to='auth.Group'),
        ),
    ]
