# Generated by Django 2.2.1 on 2019-05-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0007_auto_20190529_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='role',
            new_name='roles',
        ),
    ]
