# Generated by Django 3.1.2 on 2020-11-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201107_0619'),
        ('invites', '0009_invite_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='specialty',
        ),
        migrations.AddField(
            model_name='invite',
            name='specialty',
            field=models.ManyToManyField(related_name='invites', to='users.Specialty'),
        ),
    ]
