# Generated by Django 2.2.1 on 2019-06-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='course',
        ),
    ]
