# Generated by Django 2.2.1 on 2019-06-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_add_specialty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['choice']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['specialty']},
        ),
    ]
